### ISSUE TITLE
Corregir / definir el menu para interiores de la pagina 

### ISSUE THREAD

**Issue by omero** [DrupalMexico/camp-gdl#10]
Como ejemplo dejare estos dos pantallazos en los cuales se puede apreciar como el menú de interiores queda en `transparente` como en el home y no se ve nada y al scroll se vuelve azul con la transparencia ... se mantendrá la misma funcionalidad en el resto del sitio ?

![session-detail](https://cloud.githubusercontent.com/assets/1909779/12213966/85e07fd8-b649-11e5-903f-9f0da4c212fd.png)

![session-detail2](https://cloud.githubusercontent.com/assets/1909779/12213968/8c7673a2-b649-11e5-8ca6-f21661d5feca.png)

**Comment by koffer** [comment]
Creo que el menú debería ser el mismo en cuanto a estilo y ligas, pero en el interior cada liga debería llevar a su propia pagina. El problema esta en que se tendría que poner más datos en cada pagina, para no repetir información (redacción para ser más exactos).

**Comment by jackbravo** [comment]
Parece que esto ya lo corrigió alguien. @jeyram ?
