### ISSUE TITLE
iconos no se estan mostrando.

### ISSUE THREAD

**Issue by isramv** [DrupalMexico/camp-gdl#13]
Incluir iconos en el bloque de subscribe.
como esta actualmente, font-awesome.
hay que encontrar iconos parecidos en la libreria de iconos de materialize.

dev:
![screen shot 2016-01-15 at 5 59 41 pm](https://cloud.githubusercontent.com/assets/1042722/12369730/cf7afc5a-bbb1-11e5-941c-ce64c14ccb65.png)

prod:
![screen shot 2016-01-15 at 6 00 42 pm](https://cloud.githubusercontent.com/assets/1042722/12369740/f2c4e072-bbb1-11e5-8b6d-90acc086cf4d.png)

**Comment by omero** [comment]
por que razon se quito fontawesome @isramv ? yo tomo esta task

**Comment by isramv** [comment]
Ya está cargada el font que provee iconos para materializecss, se me hace redundante tener dos fonts que proveen iconos.

**Comment by isramv** [comment]
Arreglado.
