### ISSUE TITLE
Animaciones iniciales del logo no funcionan [Firefox]

### ISSUE THREAD

**Issue by omero** [DrupalMexico/camp-gdl#16]
Al parecer el strict es bien aplicado pot firefox y no por chrome (como casi nunca) dando como resultado este warning y rompiendo la animacion y el contador.

```
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function custom.js:54:25
```

removiendo el `use strict` el problema desaparece o transformando esta funcion con parametros y llamandola desde afuera

**Comment by isramv** [comment]
Arreglado en Prod.
