### ISSUE TITLE
Fotos responsivas dentro del nodo

### ISSUE THREAD

**Issue by karimsmartica** [DrupalMexico/camp-gdl#44]
Necesitamos que las fotos que se ingresan con ckedit dentro del nodo sean responsivas.

http://www.drupalcampgdl.com/es/que-es-drupal

<img alt="Drupal 8" data-entity-type="file" data-entity-uuid="e961f246-936d-4a20-a807-7b5ca1cb963e" src="/sites/default/files/inline-images/drupal-81%20-01.png" /></p>

**Comment by isramv** [comment]
@karimsmartica este "issue" fue resuelto
