### ISSUE TITLE
Diseño de interiores para ususarios y sesiones 

### ISSUE THREAD

**Issue by omero** [DrupalMexico/camp-gdl#9]
Necesitamos los diseños de las siguientes secciones (el pantallazo actual se mostrara en el mismo orden de los checks)
- [ ] Login
- [ ] Detalle del usuario
- [ ] Formulario de sesiones para usuario autentificado
- [ ] Detalle de sesiones
- [ ] Sesiones propuestas (Listado)

![login](https://cloud.githubusercontent.com/assets/1909779/12213932/a901700e-b648-11e5-9d5f-ddb2466508bc.png)

![user](https://cloud.githubusercontent.com/assets/1909779/12213933/b2b3357e-b648-11e5-96d9-0b4b203ce493.png)

![session](https://cloud.githubusercontent.com/assets/1909779/12213935/bb3d6106-b648-11e5-96bf-8c74e643dc22.png)

![session-detail](https://cloud.githubusercontent.com/assets/1909779/12213949/124017dc-b649-11e5-9b72-9d6ca9dded72.png)

El listado no existe como tal, tambien es importante definir que bloques se quedan y cuales se van para estas respectivas secciones, existen elementos de los forms que son los que http://materializecss.com/ ya define

**Comment by isramv** [comment]
Esto ya quedo.
